### ISSUE TITLE
Create code to automatically generate Rmd files

### ISSUE THREAD

**Issue by kaybenleroll** [DublinLearningGroup/dataexpks#1]
We want the main version of the package to work via a single function that will take a data file as input and generate all the markdown and code to create a very basic version of the rmarkdown doc that will serve as a kickstarter for the data exploration.

**Comment by collinspp** [comment]
strugilng to even fork it. tried an upload instead and only allows pushed which i dont have. should wait till im home to do this.

**Comment by kaybenleroll** [comment]
Closing this, as redesigning how the Rmarkdown templates will work.
