### ISSUE TITLE
Select on line 887 relying on static column names & Section 6.2

### ISSUE THREAD

**Issue by GRoughsedge** [DublinLearningGroup/dataexpks#10]
There are static variable names, should it be changed to a select_if(is.numeric)?

There is a commented out line near the top, is this removeable?

Section 6.2: in this instance the num_data_tbl has no rows. I don't know if this is beacuse of the data or because I've selected too many columns using the select_if. If there are no rows then that block and everything below doesn't work.

**Comment by kaybenleroll** [comment]
Closing this as it seems to have been fixed.
