### ISSUE TITLE
Flag for block estimate_data_mean_covariance and below

### ISSUE THREAD

**Issue by GRoughsedge** [DublinLearningGroup/dataexpks#11]
Because there is a very real possibility for the data table in the estimate_data_mean_covariance block to produce a zero length table should there be a flag to indicate if the sections should be run? Roughly line 880 (might differ on mine due to alterations)

**Comment by kaybenleroll** [comment]
Closing as the multivariate numeric analysis has now been removed as out-of-scope for the template.

This may get reintroduced if we add other workbooks later.
