### ISSUE TITLE
line 698 condition not capturing data size

### ISSUE THREAD

**Issue by GRoughsedge** [DublinLearningGroup/dataexpks#7]
if(nrow(data_tbl) > mds_sample_count) { 
needs to be extended to be
if(nrow(data_tbl %>% filter(row_ids)) > mds_sample_count) {

**Comment by GRoughsedge** [comment]
This also applies to line 763, it is:
if(nrow(data_tbl) > tsne_sample_count) {
and it should be:
if(nrow(data_tbl) %>% filter(row_ids) > tsne_sample_count) {

**Comment by kaybenleroll** [comment]
Fixed this issue in a previous commit.
