### ISSUE TITLE
line 771 Error in Rtsne.default(X, ...) : Remove duplicates before running TSNE.

### ISSUE THREAD

**Issue by GRoughsedge** [DublinLearningGroup/dataexpks#8]
It was
data_tsne <- Rtsne(tsne_tbl %>% select(one_of(numeric_vars)))
I suggest
data_tsne <- Rtsne(unique(tsne_tbl %>% select(one_of(numeric_vars))))

**Comment by GRoughsedge** [comment]
Line 787 is also affected

**Comment by kaybenleroll** [comment]
Closing this because the jitter in the numeric variables solves this problem.
