### ISSUE TITLE
Issue in lines 773-4 and 789-90 

### ISSUE THREAD

**Issue by GRoughsedge** [DublinLearningGroup/dataexpks#9]
There is an issue with the relative table sizes in these lines: 

tsne_tbl$tsne_d1 <- data_tsne$Y[,1]
tsne_tbl$tsne_d2 <- data_tsne$Y[,2]

tsne_tbl is a copy of sample_tbl while data_tsne is a set of unique values from sample_tbl. This being an issue is contingent on my suggested fix for Issue #8 being correct.

**Comment by kaybenleroll** [comment]
This issues has now been fixed I believe, due to the various changes to the code that happened.
